apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-kubernetes-backend
  template:
    metadata:
      labels:
        app: test-kubernetes-backend
    spec:
      containers:
        - name: test-kubernetes-backend
          image: thejandeera/test-kubernetes-project:latest
          ports:
            - containerPort: 8080
          env:
            - name: FRONTEND_URL
              value: "http://localhost:5173"  # replace with your actual frontend URL
            - name: DATASOURCE_URL
              value: "mongodb+srv://thejandeera:Thejan12345@cluster0.dd1hdgu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
