apiVersion: v1
kind: Service
metadata:
  name: test-kubernetes-service
spec:
  selector:
    app: test-kubernetes-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
